username: henryzhao
baseurl: /
markdown: redcarpet
safe: false
highlighter: pygments
title: Henryzhao
description: 空负凌云万丈志，一生襟抱未曾开！
theme: hack
disqusname: henryzhao

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine
# those themes are all come from GitHub Pages Themes
